$font = Inter

general {
    hide_cursor = true
}


animations {
    enabled = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 8
    brightness = 0.7
    contrast = 0.9
    noise = 0.0
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %-d %B"
    color = rgba(255, 255, 255, 0.85)
    font_size = 20
    font_family = $font

    position = 0, 230
    halign = center
    valign = center
}

label {
    monitor =
    text = <span font_weight="700">$TIME</span>
    color = rgba(255, 255, 255, 0.95)
    font_size = 120
    font_family = $font

    position = 0, 140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 220px, 40px
    outline_thickness = 0
    rounding = -1

    dots_size = 0.3
    dots_spacing = 0.4
    dots_center = true

    font_family = $font
    shadow_passes = 0

    position = 0, -60
    halign = center
    valign = center
}